development: &development

  #EventFinda
  finda_user_name: "username"
  finda_password:  "123123123"

  #Redis
  redis_url:       "redis://localhost:6379/0"

test:
  <<: *development

production:

  #EventFinda
  finda_user_name: "username"
  finda_password:  "123123123"

  #Redis
  redis_url:       "redis://localhost:6379/0"
